# Bun configuration file
# This file ensures Bun buildpack detection on Koyeb

[install]
# Use exact versions from lockfile
exact = true

# Cache configuration
cache = true

# Production optimizations
production = false

[install.scopes]
# Optional: configure scoped packages if needed

[run]
# Bun runtime configuration
bun = true
