# Koyeb App Configuration
# Optimized for Bun runtime with minimal resources

name: hackerfolio-tulio

services:
  - name: web
    type: web

    # Git configuration
    git:
      repository: github.com/your-username/hackerfolio-tulio
      branch: main
      auto_deploy: true

    # Bun runtime configuration
    build:
      type: buildpack
      buildpack: https://github.com/jakeg/heroku-buildpack-bun

    # Build configuration
    build_command: bun run build:production

    # Start command - uses bundled database
    run_command: bun run start:bundled

    # Instance configuration (minimal for cost optimization)
    instance:
      type: nano # Smallest instance type

    # Scaling configuration
    scaling:
      min: 0 # Scale to zero when not used
      max: 1 # Single instance for small app

    # Port configuration
    ports:
      - port: 8000
        protocol: http

    # Environment variables (PaaS-friendly - uses bundled database)
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: '8000'
      # URLs will be auto-detected by the app
      # DATABASE_URL not set - uses bundled database in Docker image
      - name: SESSION_SECRET
        secret: session-secret
      - name: LOG_LEVEL
        value: info
      - name: GITHUB_TOKEN
        secret: github-token

    # Health check
    health_check:
      path: /api/health
      port: 8000
      initial_delay: 30
      timeout: 10
      interval: 30

    # Regions (choose closest to your users)
    regions:
      - fra # Frankfurt (Europe)
      # - was  # Washington (US East)
      # - sin  # Singapore (Asia)

# Secrets (configure these in Koyeb dashboard)
secrets:
  - name: session-secret
    # Generate: openssl rand -base64 32
  - name: github-token
    # Your GitHub personal access token (optional)
