# =============================================================================
# Development Docker Compose configuration for HackerFolio-Tulio
# For testing and development with live reload capabilities
# =============================================================================

services:
  app-dev:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
      target: builder
    container_name: hackerfolio-tulio-dev
    ports:
      - '3001:3001'
      - '5173:5173' # Vite dev server
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=3001
      - DATABASE_URL=/app/database/portfolio.db
      - CORS_ORIGINS=http://localhost:5173,http://localhost:3001
    volumes:
      # Mount source code for live development
      - ../client:/app/client
      - ../server:/app/server
      - ../shared:/app/shared
      - ../database:/app/database
      - ../package.json:/app/package.json
      - ../bun.lock:/app/bun.lock
      - ../vite.config.ts:/app/vite.config.ts
      - ../tsconfig.json:/app/tsconfig.json
      # Exclude node_modules to use container's version
      - /app/node_modules
    networks:
      - app_network
    restart: unless-stopped
    command: ['bun', 'run', 'dev']

networks:
  app_network:
    driver: bridge
    name: hackerfolio_dev_network
